### ISSUE TITLE
Expose SPS health check endpoints

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#127]
Expose the SPS endpoints for Airflow UI, API, OGC API.

Endpoints must be added to SSM parameters and alsoe be documented in Gitbook: https://unity-sds.gitbook.io/docs/mdps-overview/endpoints

Must ask CS for the latest syntax for the related SSM keys.

**Comment by LucaCinquini** [comment]
See draft PR: https://github.com/unity-sds/unity-monorepo/pull/13/files 

Must modify modules/terraform-unity-sps-airflow/main.tf and introduce 2 new SSM parameters that conform to CS’s new schema with key:
/unity/${project}/${venue}/component/

Examples for unity-venue-dev:
/unity/unity/dev/component/airflow-ui
/unity/unity/dev/component/airflow-api [TBC]
/unity/unity/dev/component/ogc-api [TBC]

**Comment by nikki-t** [comment]
I think I have pulled together all of the info that I need but would appreciate confirmation!

I am planning to modify the [Airflow Terraform](https://github.com/unity-sds/unity-sps/blob/develop/terraform-unity/modules/terraform-unity-sps-airflow/main.tf) to add in the SSM parameters needed for the health check.

Here is what I came up with for each health check endpoint:

SSM Parameter: `/unity/unity/dev/component/airflow-ui`
```json
{
    "componentName": "Airflow UI",
    "healthCheckUrl": "http://k8s-airflow-airflowi-xxx.com:5000/health",
    "landingPageUrl": "http://k8s-airflow-airflowi-xxx.com:5000"
}
```

SSM Parameter: `/unity/unity/dev/component/airflow-api`
```json
{
    "componentName": "Airflow API",
    "healthCheckUrl": "http://k8s-airflow-airflowi-xxx.com:5000/api/v1/health",
    "landingPageUrl": "http://k8s-airflow-airflowi-xxx.com:5000/api/v1"
}
```

SSM Parameter: `/unity/unity/dev/component/ogc-api`
```json
{
    "componentName": "OGC API",
    "healthCheckUrl": "http://k8s-airflow-ogcproce-xxx.com:5001/health",
    "landingPageUrl": "http://k8s-airflow-ogcproce-xxx.com:5001"
}
```

@galenatjpl - Does this look like the parameter name and format that you were expecting?

@LucaCinquini  @drewm-jpl and @jpl-btlunsfo - Is the health check URL correct for each component? Note the URLs domain is condensed for readability. Should they be https?

**Comment by LucaCinquini** [comment]
@nikki-t : the health check URLs are ok. I think for now we still need to use http until we install the SSL certificates. It all looks good to me.

**Comment by galenatjpl** [comment]
Thanks @nikki-t and @LucaCinquini .  Please note that we will have to wait a few days to test, as @hargitayjpl will have to modify some code slightly when he gets back to work (tomorrow I think)

**Comment by nikki-t** [comment]
@galenatjpl - I just created this [PR](https://github.com/unity-sds/unity-sps/pull/171) so the only place we have the parameters deployed is `unity-venue-dev`. When you are ready to test, where do you usually test and we can make sure the parameters are deployed to that environment?

@LucaCinquini - I did not update the GitBook documentation: https://unity-sds.gitbook.io/docs/mdps-overview/endpoints as I wasn't sure what the final endpoint URLs would be or what venue they would be coming from in that documentation. Is this something we should wait to update until we deploy the parameters to the various environments?

**Comment by galenatjpl** [comment]
@nikki-t we usually test in unity-venue-dev first.  @hargitayjpl will be working on some changes today, and we can test.  You can go ahead and just populate the SSM params there, if you haven't already.

Please note, I made some minor updates here:  https://github.com/unity-sds/unity-monorepo/pull/16

**Comment by nikki-t** [comment]
@galenatjpl - Great! The parameters are already deployed there so you should be all set to test.

**Comment by hargitayjpl** [comment]
@nikki-t @galenatjpl I have finished the code changes and have tested with the newly added health status endpoints, and everything is working seamlessly.

```
{
    "services": [
        {
            "componentName": "Airflow API",
            "ssmKey": "/unity/unity/dev/component/airflow-api",
            "healthCheckUrl": "http://k8s-airflow-airflowi-c40bad68c9-1900721674.us-west-2.elb.amazonaws.com:5000/api/v1/health",
            "landingPageUrl": "http://k8s-airflow-airflowi-c40bad68c9-1900721674.us-west-2.elb.amazonaws.com:5000/api/v1",
            "healthChecks": [
                {
                    "status": "HEALTHY",
                    "httpResponseCode": "200",
                    "date": "2024-07-18T16:49:08.459762"
                }
            ]
        },
        {
            "componentName": "Airflow UI",
            "ssmKey": "/unity/unity/dev/component/airflow-ui",
            "healthCheckUrl": "http://k8s-airflow-airflowi-c40bad68c9-1900721674.us-west-2.elb.amazonaws.com:5000/health",
            "landingPageUrl": "http://k8s-airflow-airflowi-c40bad68c9-1900721674.us-west-2.elb.amazonaws.com:5000/",
            "healthChecks": [
                {
                    "status": "HEALTHY",
                    "httpResponseCode": "200",
                    "date": "2024-07-18T16:49:08.472154"
                }
            ]
        },
        {
            "componentName": "hargitay test fail",
            "ssmKey": "/unity/unity/dev/component/hargitay/fail",
            "healthCheckUrl": "https://www.google.com/account/about/fail",
            "landingPageUrl": "https://www.google.com/account/about/",
            "healthChecks": [
                {
                    "status": "UNHEALTHY",
                    "httpResponseCode": "404",
                    "date": "2024-07-18T16:49:08.962610"
                }
            ]
        },
        {
            "componentName": "Management Console",
            "ssmKey": "/unity/unity/dev/component/management-console",
            "healthCheckUrl": "http://unity-dev-httpd-alb-285256043.us-west-2.elb.amazonaws.com:8080/management/api/health_checks",
            "landingPageUrl": "http://unity-dev-httpd-alb-285256043.us-west-2.elb.amazonaws.com:8080/management/ui",
            "healthChecks": [
                {
                    "status": "HEALTHY",
                    "httpResponseCode": "200",
                    "date": "2024-07-18T16:49:09.151228"
                }
            ]
        },
        {
            "componentName": "OGC API",
            "ssmKey": "/unity/unity/dev/component/ogc-api",
            "healthCheckUrl": "http://k8s-airflow-ogcproce-5b03c67e8a-1762192172.us-west-2.elb.amazonaws.com:5001/health",
            "landingPageUrl": "http://k8s-airflow-ogcproce-5b03c67e8a-1762192172.us-west-2.elb.amazonaws.com:5001/",
            "healthChecks": [
                {
                    "status": "HEALTHY",
                    "httpResponseCode": "200",
                    "date": "2024-07-18T16:49:09.185832"
                }
            ]
        }
    ]
}
```

**Comment by galenatjpl** [comment]
@hargitayjpl , this is awesome!  @nikki-t and @LucaCinquini , I believe this ticket can be closed, if you think the above result looks correct.

**Comment by LucaCinquini** [comment]
Yes this is great, please close the ticket. Thanks to both @hargitayjpl and @nikki-t .

**Comment by LucaCinquini** [comment]
@galenatjpl @nikki-t : I realized that the current syntax does not allow for multiple instances of an SPS to be created on the same venue. When I try to redeploy my SPS, I get the following error:

Error: creating SSM Parameter (/unity/unity/dev/component/airflow-ui): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
│ 
│   with module.unity-sps-airflow.aws_ssm_parameter.airflow_ui_health_check_endpoint,
│   on modules/terraform-unity-sps-airflow/main.tf line 811, in resource "aws_ssm_parameter" "airflow_ui_health_check_endpoint":
│  811: resource "aws_ssm_parameter" "airflow_ui_health_check_endpoint" {

and similar for the other parameters. I think we should modify the syntax to be:

/unity/unity/dev/component/{deployment}/airflow-ui

or even better:

/unity/unity/dev/{service_area}/{deployment}/airflow-ui

where "deployment" = "nightly", "default", "luca", "nikki",....

**Comment by LucaCinquini** [comment]
Also maybe let's set this flag to override the SSM parameters if they already exist, for any reason...

"To overwrite this value, set the overwrite option in the request to true."

**Comment by hargitayjpl** [comment]
The overwrite flag is being deprecated. Instead, you can use the lifecycle rule in your Terraform configuration:

```
resource "aws_ssm_parameter" "example" {
  name = "/some/param"
  type  = "String"
  value = "foo"

  lifecycle {
    ignore_changes = [all]
  }
}
```
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter
https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes

The CS team has been planning to switch over and use this new approach.

**Comment by galenatjpl** [comment]
Hi @LucaCinquini , I think we want to retain this prefix at a minimum:

/unity/{project}/${venue}/component/

This is because our software looks for this prefix.
I think what you want to have in the path, after that, is fine.
I don't think you actually want to overwrite though, since that would get rid of valid endpoints.  I think what you want to do, is just make the key unique, which avoids the need to overwrite.

I would be tempted to have something like this:
`/unity/unity/dev/component/airflow-ui-${deployment}`
or
`/unity/unity/dev/component/{deployment}/airflow-ui`

**Comment by LucaCinquini** [comment]
Thanks for the feedback @galenatjpl . @nikki-t let's go with this syntax:

/unity/unity/dev/component/{deployment}/airflow-ui

As for overriding, that is needed only in the case there are some left-over SSM parameters from a failed "destruction" phase. It wouldn't override any valid endpoints, and it's all specific to a "deployment".

**Comment by nikki-t** [comment]
@LucaCinquini - I will update the SSM parameters with the new format: `/unity/unity/dev/component/{deployment}/airflow-ui`. Do you want me to also define the lifecycle block so that the SSM parameters can be overwritten?

**Comment by LucaCinquini** [comment]
If not too difficult, I personally would...
Thanks, L

**Comment by LucaCinquini** [comment]
PR issued and approved, closing ticket.

**Comment by LucaCinquini** [comment]
Actually I realized that we also need to add the "counter" field to the endpoint keys?

For example: /unity/unity/dev/component/{deployment}/{counter}/airflow-ui

**Comment by nikki-t** [comment]
I will update the endpoints to include the counter.
