### ISSUE TITLE
Create test to deploy, execute and undeploy the CWL DAG

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#131]
Add a test to the unity-sps-ogc-processes-api repository that:

o Registers this DAG: https://github.com/unity-sds/unity-sps/blob/develop/airflow/dags/cwl_dag.py

o Execute a DAG run with the default parameters (for now):

DEFAULT_CWL_WORKFLOW = (
    "https://raw.githubusercontent.com/unity-sds/unity-sps-workflows/main/demos/echo_message.cwl"
)
DEFAULT_CWL_ARGUMENTS = json.dumps({"message": "Hello Unity"})

o Waits for the DAG run to finish, checks success status

o Unregisters the DAG

Later we will update the test to use non-custom parameters, such as:

cwl_arguments = "json.dumps({"message": "Bye Bye Unity"})

**Comment by LucaCinquini** [comment]
See this test for the Echo Process as an example:

https://github.com/unity-sds/unity-sps-ogc-processes-api/blob/develop/unity-test/test_main.py

(we could even replace that test with our more specific test for the CWL DAG).

**Comment by LucaCinquini** [comment]
Realized that the current solution won't work for nested workflows, exploring different options.

**Comment by LucaCinquini** [comment]
Using "cwltool --pack" would create a single CWL document from the top level and nested workflows, which can then be parsed and modified as needed. Unfortunately, this does not seem to work with some of our workflows that are stored in Dockstore.

For example, this command works fine:

cwltool --pack https://raw.githubusercontent.com/common-workflow-language/cwltool/main/tests/wf/nested.cwl 

But packing one of our Dockstore workflows gives an error:

cwltool --debug --pack https://raw.githubusercontent.com/unity-sds/sbg-workflows/main/L1-to-L2-e2e.cwl   

ERROR I'm sorry, I couldn't load this CWL file.
The error was: 
Traceback (most recent call last):
  File "/Users/cinquini/PycharmProjects/unity-sps/.venv/lib/python3.9/site-packages/cwltool/main.py", line 1114, in main
    print(print_pack(loadingContext, uri), file=stdout)
  File "/Users/cinquini/PycharmProjects/unity-sps/.venv/lib/python3.9/site-packages/cwltool/main.py", line 633, in print_pack
    packed = pack(loadingContext, uri)
  File "/Users/cinquini/PycharmProjects/unity-sps/.venv/lib/python3.9/site-packages/cwltool/pack.py", line 265, in pack
    v = rewrite_inputs[r]
KeyError: 'http://awslbdockstorestack-lb-1429770210.us-west-2.elb.amazonaws.com:9998/api/ga4gh/trs/v2/tools/%23workflow%2Fdockstore.org%2Fmike-gangl%2FSBG-unity-fractional-cover/versions/2/PLAIN-CWL/descriptor/%2FDockstore.cwl#sbg-unity-fractional-cover'

Probably because of the "#" in the URL. Can that be avoided?

**Comment by nikki-t** [comment]
@LucaCinquini - Is this comment meant for #186 ? Also, could we encode the HTML URL `#` sign for the Dockstore URLs? Maybe:

`http://awslbdockstorestack-lb-1429770210.us-west-2.elb.amazonaws.com:9998/api/ga4gh/trs/v2/tools/%23workflow%2Fdockstore.org%2Fmike-gangl%2FSBG-unity-fractional-cover/versions/2/PLAIN-CWL/descriptor/%2FDockstore.cwl%23sbg-unity-fractional-cover`

I am going to do a little testing this morning (9/3).
