### ISSUE TITLE
[Task] Update the SSM parameters used by SPS

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#14]
Galen reported that the SPS is using a couple of SSM keys that need to be updated to the new convention established by U-CS. Specifically:

 
Title: Update SSM params to be conformant with naming standards
Description:
 
/unity/account/network/subnet_list
NEEDS TO BE CHANGED TO:
/unity/cs/account/network/subnet_list
 
/unity/account/network/vpc_id
NEEDS TO BE CHANGED TO:
/unity/cs/account/network/vpc_id
 
These are referenced in the SPS terraform scripts, and that’s what SPS needs to change.
 
For reference, you can see exactly what U-CS creates in this script:
https://github.com/unity-sds/unity-cs-infra/blob/main/nightly_tests/set_deployment_ssm_params.sh

**Comment by jpl-btlunsfo** [comment]
Should be fixed by unity-sds/unity-cs-infra#75
