### ISSUE TITLE
[Bug]: Upgrade EKS 1.27 AMIs

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-sps#159]
MCP ticket was sent to me- cc'ed @LucaCinquini on them. A few ec2 instances in various venues are using an AMI that will be deprecated soon (aml2-eks-1-27) . We must upgrade to a new blessed EKS AMI (aml2-eks-1-[28-30]).

| venue | ec2 ID | 
| ---- | ---- | 
|  Unity-SBG-Dev	 |  i-0ab695b36a48c98f8 |
|  Unity-SBG-Dev	|  i-0e501c35bee15e723 |
| Unity-SIPS-test   |  i-0097737f67bb24127	|
| Unity-SIPS-test   |  i-0983dd05d02bcc622  |
| Unity-SIPS-test   | i-03fe3372a3193b5ad	  |
| Unity-Venue-Ops | 	i-06aa40b7bf5eb3360	| 
| Unity-Venue-Ops	| i-0f0ec6eb6f1ca5be6	| 
| Unity-Venue-Dev	| i-0012730114f0f3887	| 
| Unity-Venue-Dev	| i-0202bda805a439cd4| 
| Unity-Venue-Dev	| i-0530656128821d57f	| 
| Unity-Venue-Dev	| i-06b5a9fc49ba5314f	| 
| Unity-Venue-Dev	| i-0c7e4ae0378e55335	| 
| Unity-Venue-Dev	| i-0dfbbde73efb49548	| 
| Unity-Venue-Dev	| i-0f116f943813f00ab	| 
| Unity-Venue-Test	| i-06b736060d3f6c491	| 
| Unity-Venue-Test	| i-0a0b9654930e9d58a	| 
| Unity-Venue-Test| 	i-0f4ab8002d597dd61	| 

For Unity-sips-test, we might want to clear that out completely as that seems to be HySDS deployments.

**Comment by LucaCinquini** [comment]
@drewm-jpl : please take down SPS+EKS from Unity-SBG-Dev and Unity-SIPS-test. I can take care of upgrading the deployments on unity-vebnue-dev and unity-venue-test.

**Comment by LucaCinquini** [comment]
unity-venue-dev and unity-venue-test have been upgraded to the latest 1.29 AMI

**Comment by LucaCinquini** [comment]
All SPS instances that contained the obsolete AMI have been destroyed.
The following venues have been upgraded to the latest 1.29 AMI:
o unity-venue-dev
o unity-venue-ops
o unity-SBG-dev
