### ISSUE TITLE
[Documentation]: Document programmatic submission via Airflow API

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#212]
Write a GitBook page that contains instructions and examples on how to submit an SPS job using the Airflow API:
- with the CURL client
- with a Python script
Use the cwl_dag.py as the example DAG.

Risks: none
Dependencies: none
Tests: none

**Comment by rtapella** [comment]
I am actually not sure we want to document this.. shouldn't we be pushing every Unity user towards the OGC API? That way they're writing something that can be used across any compliant ADES (e.g. Unity-HySDS, Unity-Airflow, Unity-HECC, etc.)

**Comment by LucaCinquini** [comment]
My understanding is that the ASIPS users have asked to use the Airflow API...

**Comment by LucaCinquini** [comment]
We decided that the official Airflow documentation is enough. If people ask for specific Unity examples on how to use the Airflow API, we will provide them. Closing for now.
