### ISSUE TITLE
[New Feature]: Stage-In Task

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#220]
Write a DAG/Task that invokes the DS Docker container to stage-in data from the DS catalog.
Eventually this Task needs to be executed as part of the new Application Package CWL DAG, and followed by the Process task.

**Comment by LucaCinquini** [comment]
Nga provided examples of 2 CWL workflows for stage-in - when data is downloaded from a DAAC or from Unity:

https://github.com/unity-sds/unity-data-services/tree/cwl-examples/cwl

We can start by creating a DAG Task that - depends on what the user selects - will invoke one or the other CWL, staging data to EFS so it can be used by the sub-sequent Process task.

**Comment by LucaCinquini** [comment]
Suggested steps:
o Create a new DAG called cwl_dag_new.py with -initially- the following tasks:
o A "setup task" that will expose 2 parameters:
- stack_json_url
- input_location: "unity" or "daac"
o Plus the standard paraneters for memory, disk, cpu:
- request_memory
- request_disk
- request_cpu
- use_ecr
o Depending on input_location, the "cwl_workflow" parameter is set to https://github.com/unity-sds/unity-data-services/blob/cwl-examples/cwl/stage-in-unity/stage-in.cwl or https://github.com/unity-sds/unity-data-services/blob/cwl-examples/cwl/stage-in-daac/stage-in.cwl (use the raw URLs)
o I think the "download_dir" parameters can be hardwired to "granules" or "input" or whatever
o Then invoke the "cwl_task" which will write to  /scratch/granules or /scratch/input
o In the "cleanup" task first list the content of the "local_dir" directory, then erase (for now)

Note that the other parameters such as: "unity_client_id" should be retrieved from SSM - see example: 

https://github.com/unity-sds/unity-sps/blob/95dad09ea661f4b37b1aa000f29b33c605ded554/airflow/dags/sbg_L1_to_L2_e2e_cwl_step_by_step_dag.py#L290

**Comment by nikki-t** [comment]
Here is a first draft of the stage in task: https://github.com/unity-sds/unity-sps/blob/220-stage-in-task/airflow/dags/cwl_dag_modular.py

- The CWL stage in task is defined separately from the processing task and uses the default node pool. I set memory to 4Gi and cpu to 4 for the stage in task but we may want to define different defaults. I also allowed for the specification of ephemeral storage from the DAG parameters as I imagine all tasks will want to share the same storage for data processing.
- I manually created an SSM parameter for the DS Cognito client. The parameter is: `/unity/dev/sps/cognito-uds-client-id`. We may want to request that this be added to the shared services venue so we can retrieve the user ID as we do for the Airflow webserver.
- Happy to re-organize the CWL DAG "modular" script and/or make any changes!

**Comment by LucaCinquini** [comment]
Nikki implemented and demonstrated all functionality, this part of the CWL refactoring is done.

**Comment by LucaCinquini** [comment]
@nikki-t , with regards to the questions above:

1. Yes
2. Good idea
3. We need to understand what these parameters are for - we need to ask @ngachung 
4. This is a question for the team - I am not sure what the Unity use case really is. Another thing to discuss.

**Comment by nikki-t** [comment]
@LucaCinquini - 

For 1) I will work on supporting a STAC JSON URL or file as an input parameter. 

For 3) These are parameters that I query to support the stage out task creation of a collection id (since we don't include the collection id as an input parameter). The stage out variables are documented here: https://unity-sds.gitbook.io/docs/developer-docs/data/docs/users-guide/stage-out. Maybe we want to handle either the collection id specification or the parameters that I chose to query differently?

**Comment by mike-gangl** [comment]
ok, so the project/venue are only required if the collection id doesn't have the correct format `URN:NASA:UNITY:<PROJECT>:<VENUE>:<COLLECTION_NAME>___<COLLECTION_VERSION>` i think we can make that add-on work and for now required the collection name provided to include that.

**Comment by nikki-t** [comment]
@mike-gangl - So it sounds like it would be best to pass the collection identifier in as an input parameter to the DAG? Or is this something that the DAG (or entrypoint script) should create?

The S3 bucket constant is defined in: [unity_sps_utils.py](https://github.com/unity-sds/unity-sps/blob/220-stage-in-task/airflow/plugins/unity_sps_utils.py) which is used to create the stage out job arguments in the [cwl_dag_modular.py](https://github.com/unity-sds/unity-sps/blob/df59659bc054b09d97612cb0e4c5a5078b652857/airflow/dags/cwl_dag_modular.py#L171-L189) which get passed to the [docker_cwl_entrypoint_modular.sh](https://github.com/unity-sds/unity-sps/blob/df59659bc054b09d97612cb0e4c5a5078b652857/airflow/docker/cwl/docker_cwl_entrypoint_modular.sh#L48) script which executes the stage out CWL. That may need to be defined as an SSM parameter.

But I do think the project and venue can be taken from the Airflow environment variables defined in the [helm chart](https://github.com/unity-sds/unity-sps/blob/df59659bc054b09d97612cb0e4c5a5078b652857/airflow/helm/values.tmpl.yaml#L268-L271).

Does it make sense to add back the collection id and s3 bucket as input parameters that the user provides?

**Comment by LucaCinquini** [comment]
@nikki-t : so I reread the whole thread and I agree with Mike. To recap:
o The collection ID should be specified as an input by the user
o The S3 bucket should be retrieved from SSM - there will be only one S3 bucket per venue where people upload data
Do you agree?

**Comment by nikki-t** [comment]
@LucaCinquini - I do. I am not sure how we want to capture the S3 bucket name but I can create an SSM parameter to store it for now. I think the S3 buckets are created by the marketplace so maybe there is a way to capture the value for the different venues and store it in a SSM parameter?

**Comment by LucaCinquini** [comment]
Hi @nikki-t : yes for now use any SSM key that you want. Galen is coming up with a convention and he will send an email to everybody.

**Comment by nikki-t** [comment]
Add-on work tasks to be done at a future time:

1) Allow user to pass in JSON string as STAC JSON which gets passed to the stage in task container.
2) Support Unity-hosted STAC JSON. I think this would require us to pass in a Cognito client ID and URL and we could use the STAC JSON URL to determine if we need to pull these down from the SSM parameter store and pass them to stage in.
3) If a user does not specify a collection ID in their process input arguments then a new collection ID is created from the project and venue.
