### ISSUE TITLE
[New Feature]: Publish ogc-api-python-client to PyPi

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#225]
From Mike on Slack:

FYI, unity-py, a pypi installable library relies on https://github.com/unity-sds/unity-sps-ogc-processes-api-python-client - this is know. But without the releases in api-python-client also being published we cannot publish our pacakges. Essentially, pypi doesn't let you reference a git repository as a dependency, probably because it can go away without notice. The only solution i can imagine to this is to also publish the ogc-api-python-client to pypi as well- this is rpetty light weight, adn we did it with the 1.0.0 release previously to get around the same issue
unity-sds/unity-sps-ogc-processes-api-client-python

would it be alright to publish the ogc-api-client buids as part of the release process?

https://github.com/unity-sds/unity-sps-ogc-processes-api-client-python/blob/b272f1cc24fe25347ccc21df8fc67ba4ec97838a/[pyproject.toml](https://github.com/unity-sds/unity-sps-ogc-processes-api-client-python/blob/b272f1cc24fe25347ccc21df8fc67ba4ec97838a/pyproject.toml)#L3
pyproject.toml
version = "1.0.0"

yeah, we'll update and publish ours later. you'll need to update your pyproject.tom to be the correct version, as https://pypi.org/project/unity_sps_ogc_processes_api_python_client/ already has a v1.0.0

**Comment by mike-gangl** [comment]
i've published a version previously to make this work (1.0.0) and so currently i "own" that pypi repository. I can either provide the publish tokens (i think they are org secrets in github) or add someone (a good idea) to own the repo so they can also  publish items with their own keys.

**Comment by LucaCinquini** [comment]
@drewm-jpl : could you please include documentation on how to generate a new version of the ogc-api-python-client if needed? And how to publish it to PyPi.

**Comment by drewm-jpl** [comment]
This is complete: https://pypi.org/project/unity-sps-ogc-processes-api-python-client/

**Comment by LucaCinquini** [comment]
Instructions on how to publish a PyPI package: https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives
