### ISSUE TITLE
[New Feature]: Connect Airflow to HTTPD controller to expose UI and API

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#30]
Acceptance Criteria:
o Demonstrated use of Airflow API via Unity API Gateway URL
o Demonstrated login into Airflow UI using the Unity API Gateway URL

Dependencies:
From CS: Unity HTTPD web server deployed onto the target venues (mcp-venue-dev and mcp-venue-test)

**Comment by mike-gangl** [comment]
Closing in favor of https://github.com/unity-sds/unity-sps/issues/125
