### ISSUE TITLE
[New Feature]: Integrate Airflow with Cognito authentication (and authorization?)

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#46]
Acceptance Criteria:
o Demonstrated use of Airflow API via Unity API Gateway URL
o Demonstrated login into Airflow UI using the Unity API Gateway URL

Dependencies:
From CS: Unity API Gateway deployed onto the target venues (mcp-venue-dev and mcp-venue-test)

**Comment by mike-gangl** [comment]
closing in favor for https://github.com/unity-sds/unity-sps/issues/126
