### ISSUE TITLE
Implement the WPS-T methods execute() and status()

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#61]
Description: Using the stubbed OGC API, implement the execute() method to submit a job to SPS Airflow, and the status() method to retrieve its status.

Acceptance Criteria:
o Demonstrated invocation of the execute() and status() method via any HTTP client (for example, CURL)
o Nightly test to execute and monitor a simple CWL workflow via the WPS-T API

**Comment by LucaCinquini** [comment]
Implemented by Drew and merged into develop, tested by both Luca and Mike.

**Comment by drewm-jpl** [comment]
Future work will need to be done to perform validation of the inputs and outputs based on the schema of the registered process. This should occur in the function behind the execute endpoint. Following validation, the inputs will need to be passed to the DAG run. Currently no inputs are passed through from the endpoint to the DAG run trigger.
