### ISSUE TITLE
Implement the WPS-T methods register() and unregister()

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#62]
Description: Support "registering" (and "unregistering") an application package with Airflow, so it can be later executed as a DAG.
Possibly, invoking the register() method should dynamically generate a DAG (via Lambda?) that creates the Python code to execute the application package in the shared Airflow DAG folder. The specific DAG should extend the generic CWL DAG with proper customization, such as the application package name.
The unregister() method should either remove that DAG from the shared DAG folder, or (probably better) simply disable it.

Acceptance Criteria:
o Nightly test that registers and unregisters a simple application package

**Comment by rtapella** [comment]
this supercedes https://github.com/unity-sds/unity-sps/issues/48 ?

**Comment by drewm-jpl** [comment]
I found some information regarding deploy/undeploy, it appears these will be included in OGC API - Processes - Part 2: Deploy, Replace, Undeploy (DRU), formerly known as Transactions (formerly known as WPS-T)

Right now OGC has only released version 1.0.0 of OGC API - Processes - Part 1: Core and have not yet release Part 2.

Below is a link to some info I found about Part 2, I can’t seem to find much more info about this Part 2 anywhere else on the internet:
https://github.com/opengeospatial/ogcapi-processes/tree/master/extensions/deploy_replace_undeploy

If we request access to the OGC API Roadmap we can better track the status of Part 2:
https://docs.google.com/forms/d/e/1FAIpQLSemz424GjJC6gkLvFSA7-J7gaz1ds0bzutJJcNRsSae0gLMSg/viewform

**Comment by LucaCinquini** [comment]
Thanks Drew, this is good to know. A few of us (including @mike-gangl) could request access to the Roadmap.

**Comment by rtapella** [comment]
The old wpst endpoint I have is: https://d3vc8w9zcq658.cloudfront.net/unity-sips-test/ades-wpst/processes

What's the new one I should use to test the Processes API?

**Comment by LucaCinquini** [comment]
This is the endpoint I tested today for execute() and status():

http://k8s-airflow-ogcproce-944e409e1d-1354034359.us-west-2.elb.amazonaws.com:5001

It's deployed on the unity-venue-dev, but it's not meant to be stable.

**Comment by GodwinShen** [comment]
@LucaCinquini ping for an update.  Looks like this one is moving along nicely.

**Comment by LucaCinquini** [comment]
@drewm-jpl is making great progress on this: he enabled GitSync to synchronize the DAGs in a repository to the dags-catalog folder that is deployed with the SPS. He is now working on preventing race-conditions between updates by locking the database when a client makes a request.

**Comment by GodwinShen** [comment]
@drewm-jpl ping for status

**Comment by LucaCinquini** [comment]
Basic implementation is done, Drew needs to update the documentation

**Comment by rtapella** [comment]
So can this pull an app package from Dockstore and plop it into SPS? 
Or is this taking a DAG from Git and putting it into Airflow, and then that DAG is generic so the DAG points at Dockstore?

**Comment by LucaCinquini** [comment]
The latter.

**Comment by rtapella** [comment]
Okay thank you. I guess at this point we would not expect an algorithm developer or alg. integrator to deploy apps to SPS, because we have that generic DAG. Right?

**Comment by LucaCinquini** [comment]
Correct - under the assumption they write a single CWL that executes all of their processing.

**Comment by LucaCinquini** [comment]
Implementation is done and tested, Drew will write Gitbook documentation on how to use all OGC methods from a client perspective.

**Comment by drewm-jpl** [comment]
For full API documentation, please refer to the endpoint stored in an SSM parameter with this naming convention:
`/unity/{venue}/sps/{deployment_name}/{counter}/processing/ogc_processes/ui_url`

For example for an SPS deployment in `unity-venue-ops` with a deployment name of `nightly` and a counter of `1` the SSM parameter would be named the following:
`/unity/ops/sps/nightly/1/processing/ogc_processes/ui_url`

For documentation on how to use the API to register, execute, and unregister a process using curl commands from the command line, refer to this Gitbook page:
https://unity-sds.gitbook.io/docs/developer-docs/science-processing/docs/developers-guide/tutorial-register-execute-and-unregister-a-process-using-the-ogc-api-processes

There API has also been wrapped by `unity-py`, the documentation for interacting with the API through `unity-py` will likely be owned by the team responsible for `unity-py`.

**Comment by rtapella** [comment]
@drewm-jpl are you planning to update the unity.py part as well, or is that for @mike-gangl

**Comment by rtapella** [comment]
https://github.com/unity-sds/unity-py/issues/89

**Comment by drewm-jpl** [comment]
`unity-py` has integrated a version of the `unity-sps-ogc-processes-api-python-client` that includes the register and unregister methods. My understanding is that they are not included in any examples in the `unity-py` repo currently, however, that would eventually be the responsibility of developers of `unity-py`.

**Comment by rtapella** [comment]
Okay thanks for the links. We were trying to have service-areas own parts of unity.py and/or the tutorial notebooks (e.g., u-ds wrote the “using data” notebook) but it may be out of your scope for this release.

I think Mike was waiting for this ticket to wrap up before finishing the unity.py bit

**Comment by LucaCinquini** [comment]
Drew finalized the documentation for invoking the OGC methods:

https://app.gitbook.com/o/xZRqGQeQXJ0RP4VMj7Lq/s/UMIRhLdbRQTvMWop8Il9/developer-docs/science-processing/docs/developers-guide/tutorial-register-execute-and-unregister-a-process-using-the-ogc-api-processes

Closing the ticket.

**Comment by mike-gangl** [comment]
FYI, while we closed this ticket, the implementation is not complete and will be continued in 24.3
