### ISSUE TITLE
Nightly test for SBG end-to-end workflow

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps#65]
Description: setup a nightly test that executes the SBG end-to-end workflow

Acceptance Criteria:
o The nightly test is successfully executed in one or more target venues

**Comment by jpl-btlunsfo** [comment]
PR #84 only adds the test configuration- is updating the [sbg_L1_to_L2_e2e_cwl_step_by_step_dag.py](https://github.com/unity-sds/unity-sps/blob/develop/airflow/dags/sbg_L1_to_L2_e2e_cwl_step_by_step_dag.py) DAG to run in non-DEV venues also a requirement for this issue?

**Comment by LucaCinquini** [comment]
Just executing the SBG DAG in the Dev venue should be enough for this ticket. Were you able to run the test on Dev?

**Comment by jpl-btlunsfo** [comment]
Yep, test output attached in PR, no issues running the DAG to completion in DEV.

**Comment by LucaCinquini** [comment]
Completed, was able to trigger the integration test successfully.
