### ISSUE TITLE
Launch templates referencing expired AMIs

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-sps#70]
as per https://jaas.gsfc.nasa.gov/servicedesk/customer/portal/2/GSD-2527

Several Launch templates that point to expired AMIs:
Account | Launch Template | Name
-- | -- | --
Unity-Dev | lt-0f2deffb5caa64bce | eksctl-apigatewaytestingredux5-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-04b4a92def26d0073 | eksctl-unity-dev-sps-hysds-eks-drew-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-061807ae1ef266eaf | eksctl-unity-dev-sps-hysds-eks-luca-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-034fe546a0fff3893 | eksctl-unity-dev-sps-hysds-eks-es-nodegroup-group1NodeGroup
Unity-Dev | lt-0ec2a4b95b54a9b87 | eksctl-sps-api-gw-cluster-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-064bd24677f642c2e | eksctl-unity-dev-sps-hysds-eks-ryan-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-01285f54ebbd3305f | eksctl-unity-dev-sps-hysds-eks-namrata-nodegroup-defaultgroupNodeGroup
Unity-Dev | lt-0cc76e03f5867ddc5 | unity-dev-sps-lucas-EC2-VerdiNodeGroupLaunchTemplate
Unity-Dev | lt-0c8230f51376057e6 | unity-dev-sps-lucas-EC2-SPSPAPINodeGroupLaunchTemplate
Unity-Dev | lt-0bcb71745bd106e84 | eksctl-unity-dev-sps-hysds-eks-1-nodegroup-defaultgroupNodeGroup
Unity-Sips-Test | lt-0335194a1517df78b | unity-dev-dev-sps-sps-eks-tues-5-EC2-VerdiNodeGroupLaunchTemplate
Unity-Sips-Test | lt-03bfb489c8d84c4de | unity-dev-dev-sps-sps-eks-tues-5-EC2-SPSPAPINodeGroupLaunchTemplate
Unity-Test | lt-055e8dfcce5fe6d61 | eksctl-unity-test-sps-hysds-eks-dev-1-nodegroup-defaultgroupNodeGroup
Unity-Test | lt-0695819eb4ef9db88 | eksctl-unity-test-sps-hysds-eks-dev-2-nodegroup-defaultgroupNodeGroup
Unity-Test | lt-062b2ffcc60a7b2c3 | eksctl-unity-test-sps-hysds-eks-ryan-nodegroup-defaultgroupNodeGroup
Unity-Test | lt-0e11f27221e091760 | eksctl-unity-test-sps-hysds-eks-drew-nodegroup-defaultgroupNodeGroup
Unity-Test | lt-0314a83794ce969ec | eksctl-unity-test-sps-hysds-eks-nightly-nodegroup-defaultgroupNodeGroup
Unity-Test | lt-0cfee88b088434c8c | unity-test-sps-unity-test-sps-hysds-eks-nightly-EC2-SPSPAPINodeGroupLaunchTemplate
Unity-Test | lt-06c542a55def07efe | unity-test-sps-unity-test-sps-hysds-eks-nightly-EC2-VerdiNodeGroupLaunchTemplate
Unity-Test | lt-02df2e60716e0fc23 | unity-test-sps-unity-test-sps-hysds-eks-drew-EC2-SPSPAPINodeGroupLaunchTemplate
Unity-Test | lt-0bdfb5866cae96299 | unity-test-sps-unity-test-sps-hysds-eks-drew-EC2-VerdiNodeGroupLaunchTemplate

Probably best to remove this deployment entirely from unity-dev | unity-test as these are shared services accounts.

Also, we can probably take down the SIPS processing cluster; if not upgrade it to a valid AMI.

**Comment by drewm-jpl** [comment]
@mike-gangl I have deleted these Launch Templates you listed. They all corresponded to deployments that no longer existed. I'm not sure how they were orphaned or if this is still an issue with how we are destroying resources. I think I may have to do with the old Github Action we used to create EKS clusters in the past.

**Comment by mike-gangl** [comment]
Thanks Drew, i'm closing this ticket (not just marking it done!)
