### ISSUE TITLE
Add health check endpoint for Airflow/SPS

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-sps#71]
Create an SSM parameter following UCS provided naming convention /unity/healthCheck/<MARKETPLACE_ITEM>/<COMPONENT_NAME>/url and store  **airflow/health** endpoint as the URL

For UDS SSM parameter name will be **/unity/healthCheck/sps/airflow**

the SSM param should be automatically  created after a deployment of the service.

**Comment by LucaCinquini** [comment]
This seems to be the same as https://github.com/unity-sds/unity-sps/issues/60

**Comment by LucaCinquini** [comment]
Closing this ticket and moving comment to the other one.
